// Code generated by "stringer -type=LegalEntityPaymentStatus"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNBILLED-1]
	_ = x[BILLED-2]
	_ = x[PAID-3]
	_ = x[PAID_CONFIRMED-4]
	_ = x[FAILED-5]
}

const _LegalEntityPaymentStatus_name = "UNBILLEDBILLEDPAIDPAID_CONFIRMEDFAILED"

var _LegalEntityPaymentStatus_index = [...]uint8{0, 8, 14, 18, 32, 38}

func (i LegalEntityPaymentStatus) String() string {
	i -= 1
	if i < 0 || i >= LegalEntityPaymentStatus(len(_LegalEntityPaymentStatus_index)-1) {
		return "LegalEntityPaymentStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LegalEntityPaymentStatus_name[_LegalEntityPaymentStatus_index[i]:_LegalEntityPaymentStatus_index[i+1]]
}
