// Code generated by "stringer -type=AggregatorStatus"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Accept-1]
	_ = x[Reject-2]
	_ = x[Ready-3]
	_ = x[Confirm-4]
	_ = x[Delivered-5]
}

const _AggregatorStatus_name = "AcceptRejectReadyConfirmDelivered"

var _AggregatorStatus_index = [...]uint8{0, 6, 12, 17, 24, 33}

func (i AggregatorStatus) String() string {
	i -= 1
	if i < 0 || i >= AggregatorStatus(len(_AggregatorStatus_index)-1) {
		return "AggregatorStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AggregatorStatus_name[_AggregatorStatus_index[i]:_AggregatorStatus_index[i+1]]
}
