#name: Go
#
#on:
#  pull_request:
#
#jobs:
#
#  build:
#    runs-on: ubuntu-latest
#
#    env:
#      GO_VERSION: '1.19'
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: ${{env.GO_VERSION}}
#
#      - name: Go vet
#        run: go vet ./...
#
#      - name: tidy
#        uses: paulvollmer/action-golang-gosum@v1.0.0
#
#      - name: tests
#        run: export ENVIRONMENT=github && go test ./...
#
#      - name: staticcheck
#        uses: dominikh/staticcheck-action@v1.3.0
#        with:
#          version: "2023.1.5"
